ffmpeg_path: 'C:\Users\mfrigo\ffmpeg-master-latest-win64-gpl\bin\ffmpeg.exe'
frames_per_second: 30
real_minutes_per_video_second: 10
zoomout_nframes: 180
still_final_nframes: 60
map_extent_adjust: 0.2
osm_zoom_level_adjust: 1.2
default_route_color: r
text_color: black