ffmpeg_path: 'C:\Users\mfrigo\ffmpeg-master-latest-win64-gpl\bin\ffmpeg.exe'
frames_per_second: 1
real_seconds_per_video_second: 600
zoomout_nframes: 180
still_final_nframes: 60
map_extent_adjust: 0.2
osm_zoom_level_adjust: 1.2
default_route_color: r
text_color: black
add_trail_to_movies: False #slows down computation quite a lot
